
package com.xuxueqiang;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CbjbxxService", targetNamespace = "http://service.zjygj.com/", wsdlLocation = "file:/D:/sjfw.xml")
public class CbjbxxService_Service
    extends Service
{

    private final static URL CBJBXXSERVICE_WSDL_LOCATION;
    private final static WebServiceException CBJBXXSERVICE_EXCEPTION;
    private final static QName CBJBXXSERVICE_QNAME = new QName("http://service.zjygj.com/", "CbjbxxService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/sjfw.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CBJBXXSERVICE_WSDL_LOCATION = url;
        CBJBXXSERVICE_EXCEPTION = e;
    }

    public CbjbxxService_Service() {
        super(__getWsdlLocation(), CBJBXXSERVICE_QNAME);
    }

    public CbjbxxService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CBJBXXSERVICE_QNAME, features);
    }

    public CbjbxxService_Service(URL wsdlLocation) {
        super(wsdlLocation, CBJBXXSERVICE_QNAME);
    }

    public CbjbxxService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CBJBXXSERVICE_QNAME, features);
    }

    public CbjbxxService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CbjbxxService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Cbjbxx
     */
    @WebEndpoint(name = "CbjbxxPort")
    public Cbjbxx getCbjbxxPort() {
        return super.getPort(new QName("http://service.zjygj.com/", "CbjbxxPort"), Cbjbxx.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cbjbxx
     */
    @WebEndpoint(name = "CbjbxxPort")
    public Cbjbxx getCbjbxxPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.zjygj.com/", "CbjbxxPort"), Cbjbxx.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CBJBXXSERVICE_EXCEPTION!= null) {
            throw CBJBXXSERVICE_EXCEPTION;
        }
        return CBJBXXSERVICE_WSDL_LOCATION;
    }

}
