
package com.c503.hthj.data.services.first;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GhsjzxService", targetNamespace = "http://service.zjygj.com/",
        wsdlLocation = "http://202.107.242.115:10090/services/Ghsjzx?wsdl")
public class GhsjzxService_Service
    extends Service
{

    private final static URL GHSJZXSERVICE_WSDL_LOCATION;
    private final static WebServiceException GHSJZXSERVICE_EXCEPTION;
    private final static QName GHSJZXSERVICE_QNAME = new QName("http://service.zjygj.com/",
            "GhsjzxService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://202.107.242.115:10090/services/Ghsjzx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GHSJZXSERVICE_WSDL_LOCATION = url;
        GHSJZXSERVICE_EXCEPTION = e;
    }

    public GhsjzxService_Service() {
        super(__getWsdlLocation(), GHSJZXSERVICE_QNAME);
    }

    public GhsjzxService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GHSJZXSERVICE_QNAME, features);
    }

    public GhsjzxService_Service(URL wsdlLocation) {
        super(wsdlLocation, GHSJZXSERVICE_QNAME);
    }

    public GhsjzxService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GHSJZXSERVICE_QNAME, features);
    }

    public GhsjzxService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GhsjzxService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Ghsjzx
     */
    @WebEndpoint(name = "GhsjzxPort")
    public Ghsjzx getGhsjzxPort() {
        return super.getPort(new QName("http://service.zjygj.com/", "GhsjzxPort"), Ghsjzx.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ghsjzx
     */
    @WebEndpoint(name = "GhsjzxPort")
    public Ghsjzx getGhsjzxPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.zjygj.com/", "GhsjzxPort"), Ghsjzx.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GHSJZXSERVICE_EXCEPTION!= null) {
            throw GHSJZXSERVICE_EXCEPTION;
        }
        return GHSJZXSERVICE_WSDL_LOCATION;
    }

}
