#可以通过命令调用不同的环境
spring:
 profiles:
 #配置当前的环境：开发环境还是生产环境dev、prod
   active: dev
 main:
   banner-mode: console
 mvc:
    #页面图标favicon
   favicon:
     enabled: true
 application:
   name: nav
 redis:
    host: 192.168.1.79
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      timeout: 0


server:
  port: 8088

app:
    devModel: false
    uac:
        authUrl: https://nav.asoco.com.cn/#/home    #导航大厅地址
        token:
              keyName: token      #保存token的key
              keyUserId: userInfo  #保存用户信息的key
              expire: 30 #token 过期时间 单位:分钟

logging:
    level:warn