server:
  port: 10001
spring:
  application:
    name: spring-data-jpa
  datasource:
#    Url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root2
    password: 123456
    platform: mysql
    continue-on-error: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  entity: com.xly.spring.data.jpa.entity.AccountInfo



