
package com.c503.hthj.data.services.third;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JobService", targetNamespace = "http://service.webservice.visionagent.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JobService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")                                   //com.heqin.GetAllShipInfo    com.heqin.GetAllShipInfoResponse
    @RequestWrapper(localName = "getAllShipInfo", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.GetAllShipInfo")
    @ResponseWrapper(localName = "getAllShipInfoResponse", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.GetAllShipInfoResponse")
    public String getAllShipInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")                                             //com.heqin.QueryWorkInfo      com.heqin.QueryWorkInfoResponse
    @RequestWrapper(localName = "queryWorkInfo", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.QueryWorkInfo")
    @ResponseWrapper(localName = "queryWorkInfoResponse", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.QueryWorkInfoResponse")
    public String queryWorkInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")                                                            //com.heqin.GetAllWorkInfo   com.heqin.GetAllWorkInfoResponse
    @RequestWrapper(localName = "getAllWorkInfo", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.GetAllWorkInfo")
    @ResponseWrapper(localName = "getAllWorkInfoResponse", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.GetAllWorkInfoResponse")
    public String getAllWorkInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")                                        //com.heqin.GetAllWork  com.heqin.GetAllWorkResponse
    @RequestWrapper(localName = "getAllWork", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.GetAllWork")
    @ResponseWrapper(localName = "getAllWorkResponse", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.GetAllWorkResponse")
    public String getAllWork(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")                                                                    //com.heqin.QueryShiInfoByName   com.heqin.QueryShiInfoByNameResponse
    @RequestWrapper(localName = "queryShiInfoByName", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.QueryShiInfoByName")
    @ResponseWrapper(localName = "queryShiInfoByNameResponse", targetNamespace = "http://service.webservice.visionagent.com/", className = "com.c503.hthj.data.services.third.QueryShiInfoByNameResponse")
    public String queryShiInfoByName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
